/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ctomasin_runningdynamics_AccTrack */

#ifndef _Included_com_example_ctomasin_runningdynamics_AccTrack
#define _Included_com_example_ctomasin_runningdynamics_AccTrack
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_ctomasin_runningdynamics_AccTrack_SAMPLES_NUM
#define com_example_ctomasin_runningdynamics_AccTrack_SAMPLES_NUM 600L
/*
 * Class:     com_example_ctomasin_runningdynamics_AccTrack
 * Method:    addValues
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_com_example_ctomasin_runningdynamics_AccTrack_addValues
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
