/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ctomasin_runningdynamics_LinearAcceleration */

#ifndef _Included_com_example_ctomasin_runningdynamics_LinearAcceleration
#define _Included_com_example_ctomasin_runningdynamics_LinearAcceleration
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_ctomasin_runningdynamics_LinearAcceleration_AXIS_NUM
#define com_example_ctomasin_runningdynamics_LinearAcceleration_AXIS_NUM 3L
#undef com_example_ctomasin_runningdynamics_LinearAcceleration_G_VAL
#define com_example_ctomasin_runningdynamics_LinearAcceleration_G_VAL 9.18f
#undef com_example_ctomasin_runningdynamics_LinearAcceleration_GRAVITY_SAMPLES_NUM
#define com_example_ctomasin_runningdynamics_LinearAcceleration_GRAVITY_SAMPLES_NUM 10L
#undef com_example_ctomasin_runningdynamics_LinearAcceleration_ALPHA
#define com_example_ctomasin_runningdynamics_LinearAcceleration_ALPHA 0.8f
/*
 * Class:     com_example_ctomasin_runningdynamics_LinearAcceleration
 * Method:    linearAcceleration
 * Signature: ([F)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_example_ctomasin_runningdynamics_LinearAcceleration_linearAcceleration
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
